name: DeploymentProj
on: issues
jobs:
  GetContext:
    runs-on: ubuntu-latest
    steps:
      - name: GetContextObjectFromGithub
        run: echo "${{toJson(github)}}"
  Get-Lint-Test-and-Build:
    needs: GetContext
    runs-on: ubuntu-latest
    steps:
      - name: GetCode
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint check
        run: npm run lint
      - name: Run Test
        run: npm test
      - name: Build
        run: npm run build
  ShowStuff:
    needs: Get-Lint-Test-and-Build
    runs-on: ubuntu-latest
    steps:
      - name: showrepository
        run: echo "${{toJson(github.repositoryUrl)}}"
        
