name: DeploymentProj
on: [push, issues]
jobs:
  GetCode:
    runs-on: ubuntu-latest
    steps:
      - name: GetCode
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint check
        run: npm run lint
      - name: Run Test
        run: npm test
      - name: Build
        run: npm run build